Added Get/Set/Clear initiative modifier Resolves #581
nwn-dotnet/Anvil pull request #588
Opened 2022-10-31 22:35 UTC by pyro7r34d

Tested all three functions, all work with proper return log. Tested combat initiative rolls, modifier was applied.

2022-10-31 22:44 UTC, Jorteck requested changes
Thank you for the PR!

There's a few formatting and naming nits I've flagged, but otherwise looks really good.

2022-10-31 22:44 UTC, Jorteck commented on NWN.Anvil/src/main/API/Object/NwCreature.cs
> +      InitiativeModiferService.Value.ClearInitiativeModifer(this);
Minor nit - `modifier` spelling is inconsistent in NwCreature & the service.

I've marked the other locations below.

2022-10-31 22:44 UTC, Jorteck commented on NWN.Anvil/src/main/API/Object/NwCreature.cs
> +    public int? GetInitiativeModifer()
Modifier naming.

2022-10-31 22:44 UTC, Jorteck commented on NWN.Anvil/src/main/API/Object/NwCreature.cs
> +      InitiativeModiferService.Value.SetInitiativeModifer(this, modifier);
Modifier naming.

2022-10-31 22:44 UTC, Jorteck commented on NWN.Anvil/src/main/Services/API/Creature/InitiativeModiferService.cs
> +  public sealed unsafe class InitiativeModiferService
Modifier naming.

2022-10-31 22:44 UTC, Jorteck commented on NWN.Anvil/src/main/Services/API/Creature/InitiativeModiferService.cs
> +    private readonly FunctionHook<GetInitiativeModifer> initiativeModiferHook;
Modifier naming.

2022-10-31 22:44 UTC, Jorteck commented on NWN.Anvil/src/main/Services/API/Creature/InitiativeModiferService.cs
> +    public InitiativeModiferService(HookService hookService)
Modifier naming.

2022-10-31 22:44 UTC, Jorteck commented on NWN.Anvil/src/main/Services/API/Creature/InitiativeModiferService.cs
> +    public void ClearInitiativeModifer(NwCreature creature)
Modifier naming.

2022-10-31 22:44 UTC, Jorteck commented on NWN.Anvil/src/main/Services/API/Creature/InitiativeModiferService.cs
> +      if (initiativeModifer.HasValue)
Modifier naming.

2022-10-31 22:44 UTC, Jorteck commented on NWN.Anvil/src/main/Services/API/Creature/InitiativeModiferService.cs
> +    public void SetInitiativeModifer(NwCreature creature, Int32 mod)
Modifier naming.

2022-11-11 22:58 UTC, Jorteck requested changes

2022-11-11 22:58 UTC, Jorteck commented on NWN.Anvil/src/main/Services/API/Creature/InitiativeModifierService.cs
> +        return InternalVariables.InitiativeMod(creature);
Can reuse the variable here:

```suggestion
        return initiativeModifier.Value;
```

2022-11-11 22:58 UTC, Jorteck commented on NWN.Anvil/src/main/Services/API/Creature/InitiativeModifierService.cs
> +      if (cCreature.m_bInitiativeExpired == 1)
Prefer usage of the `ToBool()` extension instead of the int comparison.
```suggestion
      if (cCreature.m_bInitiativeExpired.ToBool())
```

2022-11-11 22:58 UTC, Jorteck commented on NWN.Anvil/src/main/Services/API/Creature/InitiativeModifierService.cs
> +        cCreature.m_bInitiativeExpired = 0;
```suggestion
        cCreature.m_bInitiativeExpired = false.ToInt();
```

2023-01-08 03:55 UTC, pyro7r34d reviewed
Updated adding requested changes, removed using system and removed extra whitespace

2023-01-08 04:05 UTC, pyro7r34d reviewed
Fixed modifer typo

2023-01-08 04:26 UTC, Jorteck approved these changes

2023-01-08 04:26 UTC, merged